import express from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI, Type } from '@google/genai';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const isProduction = process.env.NODE_ENV === 'production';
const PORT = 3000;

// Helper to clean API keys of any leading/trailing quotes often added manually in .env files
function cleanApiKey(key: string | undefined): string | undefined {
  if (!key) return undefined;
  let cleaned = key.trim();
  if ((cleaned.startsWith('"') && cleaned.endsWith('"')) || (cleaned.startsWith("'") && cleaned.endsWith("'"))) {
    cleaned = cleaned.slice(1, -1);
  }
  return cleaned.trim();
}

// Lazy initialization of Gemini SDK
let aiClient: GoogleGenAI | null = null;

function getGeminiClient(customKey?: string): GoogleGenAI {
  const apiKey = cleanApiKey(customKey || process.env.GEMINI_API_KEY);
  if (!apiKey || apiKey === 'MY_GEMINI_API_KEY' || apiKey === '') {
    throw new Error('GEMINI_API_KEY is not configured. Please configure it in the Workspace API Settings or the Settings menu.');
  }
  if (customKey) {
    return new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });
  }
  if (!aiClient) {
    aiClient = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });
  }
  return aiClient;
}

// Groq API client helper utilizing standard fetch for zero runtime dependencies
async function callGroqChat(
  messages: any[],
  systemInstruction?: string,
  jsonMode: boolean = false,
  customKey?: string,
  temperature?: number,
  maxTokens?: number,
  model?: string
): Promise<string> {
  const apiKey = cleanApiKey(customKey || process.env.GROQ_API_KEY);
  if (!apiKey || apiKey === 'YOUR_GROQ_API_KEY' || apiKey === '') {
    throw new Error('GROQ_API_KEY is not configured. Please set your Groq API key in the Workspace API Settings menu.');
  }

  const payloadMessages = [];
  if (systemInstruction) {
    payloadMessages.push({ role: 'system', content: systemInstruction });
  }
  payloadMessages.push(...messages);

  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model: model || 'llama-3.3-70b-versatile',
      messages: payloadMessages,
      temperature: temperature !== undefined ? Number(temperature) : 0.7,
      max_tokens: maxTokens !== undefined ? Number(maxTokens) : undefined,
      response_format: jsonMode ? { type: 'json_object' } : undefined
    })
  });

  if (!response.ok) {
    const errText = await response.text();
    let parsedErr;
    try {
      parsedErr = JSON.parse(errText);
    } catch {
      parsedErr = null;
    }
    const errMsg = parsedErr?.error?.message || errText || 'Groq API request failed.';
    throw new Error(`Groq API Error: ${errMsg}`);
  }

  const data = await response.json();
  const content = data.choices?.[0]?.message?.content;
  if (!content) {
    throw new Error('Groq returned an empty response.');
  }
  return content;
}

// Normalize keys of optimized prompt JSON generated by AI
function normalizeOptimizedPrompt(raw: any) {
  const result: any = {};
  
  // Helper to find a value by case-insensitive and spacing/underscore-insensitive key matching
  const findValue = (keys: string[]): string => {
    for (const key of keys) {
      if (raw[key] !== undefined) return String(raw[key]);
      
      const normalizedTarget = key.toLowerCase().replace(/[^a-z0-9]/g, '');
      for (const rawKey of Object.keys(raw)) {
        const normalizedRawKey = rawKey.toLowerCase().replace(/[^a-z0-9]/g, '');
        if (normalizedRawKey === normalizedTarget) {
          return String(raw[rawKey]);
        }
      }
    }
    return '';
  };

  result.title = findValue(['title', 'Title', 'promptTitle']);
  result.description = findValue(['description', 'Description', 'promptDescription']);
  result.role = findValue(['role', 'Role', 'persona', 'Persona']);
  result.task = findValue(['task', 'Task', 'instruction', 'Instruction']);
  result.context = findValue(['context', 'Context', 'background', 'Background']);
  result.constraints = findValue(['constraints', 'Constraints', 'rules', 'Rules']);
  result.examples = findValue(['examples', 'Examples', 'example', 'Example', 'fewShot', 'few_shot']);
  result.outputFormat = findValue(['outputFormat', 'output_format', 'Output Format', 'OutputFormat', 'output', 'Output']);
  result.tone = findValue(['tone', 'Tone', 'style', 'Style']);
  result.successCriteria = findValue(['successCriteria', 'success_criteria', 'Success Criteria', 'SuccessCriteria', 'success', 'Success']);
  result.negativeInstructions = findValue(['negativeInstructions', 'negative_instructions', 'Negative Instructions', 'NegativeInstructions', 'negative', 'Negative']);
  
  const categoryRaw = findValue(['category', 'Category']).toLowerCase().trim();
  const allowedCategories = ['development', 'writing', 'design', 'debugging', 'business', 'other'];
  result.category = allowedCategories.includes(categoryRaw) ? categoryRaw : 'other';

  return result;
}

async function startServer() {
  const app = express();
  app.use(express.json());

  // API endpoints
  
  // 1. Optimize / Expand Goal into a fully structured Prompt
  app.post('/api/optimize-prompt', async (req: express.Request, res: express.Response) => {
    try {
      const { goal, category, provider, model, temperature } = req.body;
      const geminiHeader = req.headers['x-gemini-key'] as string | undefined;
      const groqHeader = req.headers['x-groq-key'] as string | undefined;

      if (!goal) {
        res.status(400).json({ error: 'A starting prompt or goal is required.' });
        return;
      }

      const promptText = `You are a master of Prompt Engineering. Your task is to take a raw user goal or basic prompt and transform it into a highly professional, structured, battle-tested prompt. 
Decompose and expand the following user goal into the 9 essential parts of a professional prompt:
- Title: A short, catchy, professional title for the prompt.
- Description: A clear 1-sentence description of what this prompt achieves.
- Role: An elite expert persona who is best suited to perform this task.
- Task: The exact, highly specific action the AI must take.
- Context: The underlying scenario, why it matters, and high stakes that justify this task.
- Constraints: The rules, limitations, and requirements to keep the AI focused.
- Examples: A mock input/output example that demonstrates the expected behavior.
- Output Format: Precise template, headings, or table layouts for the response.
- Tone: The exact attitude, voice, and stylistic feel of the response.
- Success Criteria: Quantitative or qualitative milestones that define a perfect response.
- Negative Instructions: Explicit warnings of what the AI MUST NOT do (to prevent common hallucinations or bad habits).

Here is the user's raw goal:
"${goal}"

Suggest an appropriate category from: 'development', 'writing', 'design', 'debugging', 'business', 'other' (the user suggested: "${category || ''}").

Return the result as a raw JSON object matching the requested schema. Ensure all fields are fully populated with rich, valuable, professional content. Do not leave any fields blank or use placeholder text.`;

      if (provider === 'groq') {
        const responseText = await callGroqChat(
          [{ role: 'user', content: promptText }],
          'You are an advanced prompt engineering system that outputs valid, well-formed JSON objects representing elite-tier structured prompts. Never add markdown wrappers or generic text in your JSON output. Return only valid raw JSON.',
          true,
          groqHeader,
          temperature !== undefined ? Number(temperature) : undefined,
          undefined,
          model
        );
        let cleanedResponse = responseText.trim();
        if (cleanedResponse.startsWith('```json')) {
          cleanedResponse = cleanedResponse.substring(7);
        }
        if (cleanedResponse.startsWith('```')) {
          cleanedResponse = cleanedResponse.substring(3);
        }
        if (cleanedResponse.endsWith('```')) {
          cleanedResponse = cleanedResponse.substring(0, cleanedResponse.length - 3);
        }
        cleanedResponse = cleanedResponse.trim();
        const rawJson = JSON.parse(cleanedResponse);
        const optimizedPrompt = normalizeOptimizedPrompt(rawJson);
        res.json(optimizedPrompt);
        return;
      }

      const ai = getGeminiClient(geminiHeader);
      const response = await ai.models.generateContent({
        model: model || 'gemini-3.5-flash',
        contents: promptText,
        config: {
          systemInstruction: 'You are an advanced prompt engineering system that outputs valid, well-formed JSON objects representing elite-tier structured prompts. Never add markdown wrappers or generic text in your JSON output.',
          responseMimeType: 'application/json',
          temperature: temperature !== undefined ? Number(temperature) : 0.7,
          responseSchema: {
            type: Type.OBJECT,
            required: [
              'title',
              'description',
              'role',
              'task',
              'context',
              'constraints',
              'examples',
              'outputFormat',
              'tone',
              'successCriteria',
              'negativeInstructions',
              'category'
            ],
            properties: {
              title: { type: Type.STRING, description: 'Catchy and professional name for this prompt blueprint.' },
              description: { type: Type.STRING, description: 'A clear, high-level summary of the prompt purpose.' },
              role: { type: Type.STRING, description: 'An elite, authoritative persona who will execute the prompt.' },
              task: { type: Type.STRING, description: 'The exact, detailed, primary instruction set.' },
              context: { type: Type.STRING, description: 'Background scenario, high stakes, and purpose of the action.' },
              constraints: { type: Type.STRING, description: 'Technical, structural, or logical restrictions and parameters.' },
              examples: { type: Type.STRING, description: 'A side-by-side mock Input and Output illustrating exact expectations.' },
              outputFormat: { type: Type.STRING, description: 'Strict formatting templates, headers, tables, or markdown requirements.' },
              tone: { type: Type.STRING, description: 'Stylistic tone, level of detail, and brand voice.' },
              successCriteria: { type: Type.STRING, description: 'The exact benchmarks that verify a perfect execution.' },
              negativeInstructions: { type: Type.STRING, description: 'Anti-patterns, behaviors, or words to avoid completely.' },
              category: {
                type: Type.STRING,
                description: "The domain classification.",
                enum: ['development', 'writing', 'design', 'debugging', 'business', 'other']
              }
            }
          }
        }
      });

      const responseText = response.text;
      if (!responseText) {
        throw new Error('Gemini returned an empty response.');
      }

      const rawJson = JSON.parse(responseText);
      const optimizedPrompt = normalizeOptimizedPrompt(rawJson);
      res.json(optimizedPrompt);
    } catch (error: any) {
      console.error('Error in /api/optimize-prompt:', error);
      res.status(500).json({ error: error.message || 'An error occurred during prompt optimization.' });
    }
  });

  // 1.5 Refine a single specific field of a prompt
  app.post('/api/refine-field', async (req: express.Request, res: express.Response) => {
    try {
      const { fieldName, fieldValue, title, description, provider, temperature, model } = req.body;
      const geminiHeader = req.headers['x-gemini-key'] as string | undefined;
      const groqHeader = req.headers['x-groq-key'] as string | undefined;

      if (!fieldName || !fieldValue) {
        res.status(400).json({ error: 'fieldName and fieldValue are required.' });
        return;
      }

      const promptText = `You are a master of Prompt Engineering. Optimize and professionally expand the following single field of a structured prompt template.
Context of the prompt blueprint:
- Prompt Title: "${title || 'Untitled blueprint'}"
- Prompt Description: "${description || 'No description'}"

Target Field Name: "${fieldName}"
Current Field Value: "${fieldValue}"

Your task:
Analyze this field, correct any grammatical errors, elevate the vocabulary, inject highly technical and precise requirements, and expand it into a fully formed, elite prompt directive. Keep the formatting clean and ready to drop straight in. 
Return only the newly written, optimized field text. Do not add conversational intro/outro or wrap it in JSON. Just return the clean, highly-engineered text.`;

      if (provider === 'groq') {
        const refinedText = await callGroqChat(
          [{ role: 'user', content: promptText }],
          'You are an advanced prompt refinery module. You output only the polished field content, direct and ready to be used. Never include introduction, pleasantries, or markdown headers unless they are part of the content itself.',
          false,
          groqHeader,
          temperature !== undefined ? Number(temperature) : undefined,
          undefined,
          model
        );
        res.json({ refinedValue: refinedText?.trim() || fieldValue });
        return;
      }

      const ai = getGeminiClient(geminiHeader);
      const response = await ai.models.generateContent({
        model: model || 'gemini-3.5-flash',
        contents: promptText,
        config: {
          systemInstruction: 'You are an advanced prompt refinery module. You output only the polished field content, direct and ready to be used. Never include introduction, pleasantries, or markdown headers unless they are part of the content itself.',
          temperature: temperature !== undefined ? Number(temperature) : 0.7,
        }
      });

      const refinedText = response.text;
      res.json({ refinedValue: refinedText?.trim() || fieldValue });
    } catch (error: any) {
      console.error('Error in /api/refine-field:', error);
      res.status(500).json({ error: error.message || 'An error occurred during field refinement.' });
    }
  });

  // 2. Evaluate a custom Prompt against elite engineering metrics
  app.post('/api/evaluate-prompt', async (req: express.Request, res: express.Response) => {
    try {
      const { provider, model, temperature, ...promptData } = req.body;
      const geminiHeader = req.headers['x-gemini-key'] as string | undefined;
      const groqHeader = req.headers['x-groq-key'] as string | undefined;

      if (!promptData || !promptData.task) {
        res.status(400).json({ error: 'Invalid prompt data. The prompt must contain at least a Task.' });
        return;
      }

      const evaluationPrompt = `You are a Senior Prompt Engineering Auditor. Review this prompt structure, assign score metrics, identify key strengths, critical weaknesses, and provide surgical suggestions for improvements with concrete before/after text blocks.

Here is the structured prompt under review:
- Title: ${promptData.title}
- Role: ${promptData.role}
- Task: ${promptData.task}
- Context: ${promptData.context}
- Constraints: ${promptData.constraints}
- Examples: ${promptData.examples}
- Output Format: ${promptData.outputFormat}
- Tone: ${promptData.tone}
- Success Criteria: ${promptData.successCriteria}
- Negative Instructions: ${promptData.negativeInstructions}

Perform a rigorous check across four dimensions (rated 1 to 10):
1. Clarity (Is the goal unambiguous?)
2. Completeness (Are all 9 components present and contributing?)
3. Specificity (Does it avoid vague modifiers like "good", "fast", "modern"?)
4. Safety (Does it shield against jailbreaks and include protective negative instructions?)

Provide highly detailed actionable suggestions for fields that are weak. For example, if constraints or negative instructions are too short, show exactly how to expand them.
Return a structured JSON output matching the schema.`;

      if (provider === 'groq') {
        const responseText = await callGroqChat(
          [{ role: 'user', content: evaluationPrompt }],
          'You are a professional prompt quality grader. You return rigorous, objective visual audit results in structured JSON. Be highly constructive but strict; average prompts should score between 60-75. Reserve high scores (90+) for truly immaculate prompts. Return only valid raw JSON.',
          true,
          groqHeader,
          temperature !== undefined ? Number(temperature) : undefined,
          undefined,
          model
        );
        let cleanedResponse = responseText.trim();
        if (cleanedResponse.startsWith('```json')) {
          cleanedResponse = cleanedResponse.substring(7);
        }
        if (cleanedResponse.startsWith('```')) {
          cleanedResponse = cleanedResponse.substring(3);
        }
        if (cleanedResponse.endsWith('```')) {
          cleanedResponse = cleanedResponse.substring(0, cleanedResponse.length - 3);
        }
        cleanedResponse = cleanedResponse.trim();
        const evaluation = JSON.parse(cleanedResponse);
        res.json(evaluation);
        return;
      }

      const ai = getGeminiClient(geminiHeader);
      const response = await ai.models.generateContent({
        model: model || 'gemini-3.5-flash',
        contents: evaluationPrompt,
        config: {
          systemInstruction: 'You are a professional prompt quality grader. You return rigorous, objective visual audit results in structured JSON. Be highly constructive but strict; average prompts should score between 60-75. Reserve high scores (90+) for truly immaculate prompts.',
          responseMimeType: 'application/json',
          temperature: temperature !== undefined ? Number(temperature) : 0.7,
          responseSchema: {
            type: Type.OBJECT,
            required: ['overallScore', 'dimensions', 'strengths', 'weaknesses', 'suggestions', 'verdict'],
            properties: {
              overallScore: { type: Type.INTEGER, description: 'Overall grade from 0 to 100.' },
              dimensions: {
                type: Type.OBJECT,
                required: ['clarity', 'completeness', 'specificity', 'safety'],
                properties: {
                  clarity: { type: Type.INTEGER, description: 'Rating 1-10 for objective clarity.' },
                  completeness: { type: Type.INTEGER, description: 'Rating 1-10 for how well all 9 structural blocks are integrated.' },
                  specificity: { type: Type.INTEGER, description: 'Rating 1-10 for exact parameters and concrete guidelines.' },
                  safety: { type: Type.INTEGER, description: 'Rating 1-10 for defensive formatting against loose interpretations.' }
                }
              },
              strengths: {
                type: Type.ARRAY,
                items: { type: Type.STRING },
                description: '3 clear, specific elements where this prompt excels.'
              },
              weaknesses: {
                type: Type.ARRAY,
                items: { type: Type.STRING },
                description: 'Areas of ambiguity, brevity, or loose specifications.'
              },
              suggestions: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  required: ['field', 'recommendation'],
                  properties: {
                    field: { type: Type.STRING, description: 'The specific field key (e.g. constraints, negativeInstructions, context) or general.' },
                    recommendation: { type: Type.STRING, description: 'Direct instruction of what needs adding.' },
                    beforeAfter: {
                      type: Type.OBJECT,
                      required: ['before', 'after'],
                      properties: {
                        before: { type: Type.STRING, description: 'A snippet of the original text.' },
                        after: { type: Type.STRING, description: 'The recommended replacement snippet.' }
                      }
                    }
                  }
                }
              },
              verdict: { type: Type.STRING, description: 'A concise 2-sentence summary executive summary of the prompt quality.' }
            }
          }
        }
      });

      const responseText = response.text;
      if (!responseText) {
        throw new Error('Gemini returned an empty evaluation.');
      }

      const evaluation = JSON.parse(responseText);
      res.json(evaluation);
    } catch (error: any) {
      console.error('Error in /api/evaluate-prompt:', error);
      res.status(500).json({ error: error.message || 'An error occurred during prompt evaluation.' });
    }
  });

  // 3. Test Sandbox Simulator endpoint
  app.post('/api/test-sandbox', async (req: express.Request, res: express.Response) => {
    try {
      const { systemPrompt, messages, provider, temperature, maxTokens, model } = req.body;
      const geminiHeader = req.headers['x-gemini-key'] as string | undefined;
      const groqHeader = req.headers['x-groq-key'] as string | undefined;

      if (!systemPrompt) {
        res.status(400).json({ error: 'System prompt is required to test the sandbox.' });
        return;
      }
      if (!messages || !Array.isArray(messages)) {
        res.status(400).json({ error: 'An array of messages is required.' });
        return;
      }

      if (provider === 'groq') {
        const formattedMessages = messages.map((m: any) => ({
          role: m.role === 'user' ? 'user' : 'assistant',
          content: m.content
        }));
        const text = await callGroqChat(
          formattedMessages,
          systemPrompt,
          false,
          groqHeader,
          temperature !== undefined ? Number(temperature) : undefined,
          maxTokens !== undefined ? Number(maxTokens) : undefined,
          model
        );
        res.json({ content: text || 'The simulated model returned an empty response.' });
        return;
      }

      const ai = getGeminiClient(geminiHeader);

      // Convert messages to Gemini SDK expected format: { role: 'user' | 'model', parts: [{ text: string }] }
      // The last message is the current query.
      const contents = messages.map((m: any) => ({
        role: m.role === 'user' ? 'user' : 'model',
        parts: [{ text: m.content }]
      }));

      const response = await ai.models.generateContent({
        model: model || 'gemini-3.5-flash',
        contents: contents,
        config: {
          systemInstruction: systemPrompt,
          temperature: temperature !== undefined ? Number(temperature) : 0.7,
          maxOutputTokens: maxTokens !== undefined ? Number(maxTokens) : undefined,
        }
      });

      const text = response.text;
      res.json({ content: text || 'The simulated model returned an empty response.' });
    } catch (error: any) {
      console.error('Error in /api/test-sandbox:', error);
      res.status(500).json({ error: error.message || 'An error occurred during the sandbox simulation.' });
    }
  });

  // 4. Check if APIs are active
  app.get('/api/check-key', (req: express.Request, res: express.Response) => {
    const geminiKey = cleanApiKey(req.headers['x-gemini-key'] as string || process.env.GEMINI_API_KEY);
    const groqKey = cleanApiKey(req.headers['x-groq-key'] as string || process.env.GROQ_API_KEY);
    
    const geminiConfigured = !!geminiKey && geminiKey !== 'MY_GEMINI_API_KEY' && geminiKey !== '';
    const groqConfigured = !!groqKey && groqKey !== 'YOUR_GROQ_API_KEY' && groqKey !== '';
    
    res.json({ 
      configured: geminiConfigured, // fallback compatibility
      geminiConfigured,
      groqConfigured
    });
  });

  // Vite development vs Production asset serving
  if (!isProduction) {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running at http://localhost:${PORT}`);
  });
}

startServer().catch((err) => {
  console.error('Failed to start server:', err);
});
